### ISSUE TITLE
utilize already existing gitignore file

### ISSUE THREAD

**Issue by tom-spalding** [dsimidzija/vim-nerdtree-ignore#1]
Hi! Is it possible for this plugin to by default use a `.gitignore` by default instead of creating the new dotfile? Or can we do something like `ln ".nerdtreeignore" ".gitignore"`?

**Comment by dsimidzija** [comment]
I don't think that's a good idea, if you look at `:help NERDTreeIgnore`, you can see it supports custom flags which are not available in `.gitignore`. Plus the [patterns](https://git-scm.com/docs/gitignore#_pattern_format) themselves are probably significantly different for both files, so it would require some sort of conversion.

Last but not least, the two lists don't have to be equal, someone may want to see some files in the tree without keeping them under git, and vice versa. For example you may have `.env` file in `.gitignore` but visible in NERDTree, right?

**Comment by tom-spalding** [comment]
I see what you mean. I suppose what I really want is to suppress/grey-out items listed in the `.gitignore` automatically, which would require overriding syntax highlighted items in another project such as `nerdtree` itself or `nerdtree-git-plugin`, etc. Thanks, marking this as resolved.
